/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
var sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '📅 Weekly Reports',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'weekly',
        },
      ],
    },
    {
      type: 'category',
      label: 'Literature Reviews',
      collapsed: false,
      items: [
        'reviews/intro',
        {
          type: 'category',
          label: 'CyberGym',
          collapsed: true,
          items: [
            'reviews/cybergym/intro',
            {
              type: 'category',
              label: 'Getting Started',
              items: [
                'reviews/cybergym/getting-started/installation',
                {
                  type: 'category',
                  label: 'Quick-Start',
                  items: [
                    'reviews/cybergym/getting-started/quick-start/local_machine',
                    'reviews/cybergym/getting-started/quick-start/local_machine2',
                    'reviews/cybergym/getting-started/quick-start/poc_generation',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Theory',
              items: [
                'reviews/cybergym/theory/overview',
                'reviews/cybergym/theory/api',
                'reviews/cybergym/theory/architecture',
                'reviews/cybergym/theory/cybergym-method',
                'reviews/cybergym/theory/evaluation-findings',
              ],
            },
            {
              type: 'category',
              label: 'Experiments',
              items: [
                'reviews/cybergym/experiments/input-dataset',
                'reviews/cybergym/experiments/LLM-models',
                'reviews/cybergym/experiments/cybench',
                'reviews/cybergym/experiments/codex',
                'reviews/cybergym/experiments/enigma',
                'reviews/cybergym/experiments/openhands',
                'reviews/cybergym/experiments/poc-generation',
                'reviews/cybergym/experiments/poc-verification',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'SEC-Bench',
          collapsed: true,
          items: [
            'reviews/sec-bench/intro',
            {
              type: 'category',
              label: 'Theory',
              items: [
                'reviews/sec-bench/theory/overview',
                'reviews/sec-bench/theory/secbench-method',
                'reviews/sec-bench/theory/evaluation-findings',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'FaultLine',
          collapsed: true,
          items: [
            'reviews/faultline/intro',
            {
              type: 'category',
              label: 'Theory',
              items: [
                'reviews/faultline/theory/overview',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'CVE-Bench',
          collapsed: true,
          items: [
            'reviews/cve-bench/intro',
            {
              type: 'category',
              label: 'Theory',
              items: [
                'reviews/cve-bench/theory/overview',
              ],
            },
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;