/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '📅 Weekly Reports',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'weekly',
        },
      ],
    },
    {
      type: 'category',
      label: 'CyberGym',
      collapsed: true,
      items: [
        'cybergym/intro',
        {
          type: 'category',
          label: 'Getting Started',
          items: [
            'cybergym/getting-started/installation',
            {
              type: 'category',
              label: 'Quick-Start',
              items: [
                'cybergym/getting-started/quick-start/local_machine',
                'cybergym/getting-started/quick-start/local_machine2',
                'cybergym/getting-started/quick-start/poc_generation',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Theory',
          items: [
            'cybergym/theory/overview',
            'cybergym/theory/api',
            'cybergym/theory/architecture',
            'cybergym/theory/cybergym-method',
            'cybergym/theory/evaluation-findings',
          ],
        },
        {
          type: 'category',
          label: 'Experiments',
          items: [
            'cybergym/experiments/input-dataset',
            'cybergym/experiments/LLM-models',
            'cybergym/experiments/cybench',
            'cybergym/experiments/codex',
            'cybergym/experiments/enigma',
            'cybergym/experiments/openhands',
            'cybergym/experiments/poc-generation',
            'cybergym/experiments/poc-verification',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'SEC-Bench',
      collapsed: true,
      items: [
        'sec-bench/intro',
        {
          type: 'category',
          label: 'Theory',
          items: [
            'sec-bench/theory/overview',
            'sec-bench/theory/secbench-method',
            'sec-bench/theory/evaluation-findings',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'FaultLine',
      collapsed: true,
      items: [
        'faultline/intro',
        {
          type: 'category',
          label: 'Theory',
          items: [
            'faultline/theory/overview',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'CVE-Bench',
      collapsed: true,
      items: [
        'cve-bench/intro',
        {
          type: 'category',
          label: 'Theory',
          items: [
            'cve-bench/theory/overview',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;